/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"Geist Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'monospace'],
      },
      colors: {
        ink: '#171717',
        body: '#4d4d4d',
        mute: '#888888',
        hairline: '#ebebeb',
        'hairline-strong': '#a1a1a1',
        canvas: '#ffffff',
        'canvas-soft': '#fafafa',
        'canvas-soft-2': '#f5f5f5',
        link: '#0070f3',
        'link-deep': '#0761d1',
        'link-bg-soft': '#d3e5ff',
        success: '#0070f3',
        error: '#ee0000',
        'error-soft': '#f7d4d6',
        'error-deep': '#c50000',
        warning: '#f5a623',
        'warning-soft': '#ffefcf',
        'warning-deep': '#ab570a',
        violet: '#7928ca',
        'violet-soft': '#d8ccf1',
        'violet-deep': '#4c2889',
        cyan: '#50e3c2',
        'cyan-soft': '#aaffec',
        'cyan-deep': '#29bc9b',
        'highlight-pink': '#ff0080',
        'highlight-magenta': '#eb367f',
        'gradient-develop-start': '#007cf0',
        'gradient-develop-end': '#00dfd8',
        'gradient-preview-start': '#7928ca',
        'gradient-preview-end': '#ff0080',
        'gradient-ship-start': '#ff4d4d',
        'gradient-ship-end': '#f9cb28',
      },
      borderRadius: {
        'pill-sm': '64px',
        pill: '100px',
      },
      spacing: {
        section: '192px',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        gradient: 'gradient 8s ease infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        gradient: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
      },
      boxShadow: {
        'vercel-sm': '0px 1px 1px rgba(0,0,0,0.05), 0px 2px 2px rgba(0,0,0,0.10)',
        'vercel-md': '0px 2px 2px rgba(0,0,0,0.10), 0px 8px 8px -8px rgba(0,0,0,0.10)',
        'vercel-lg': '0px 2px 2px rgba(0,0,0,0.10), 0px 8px 16px -4px rgba(0,0,0,0.10)',
        'vercel-xl': '0px 1px 1px rgba(0,0,0,0.05), 0px 8px 16px -4px rgba(0,0,0,0.10), 0px 24px 32px -8px rgba(0,0,0,0.15)',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
